import { useParticalAccount } from "@partical/react-partical";
import { Box, Button, IconChevronUp, IconEth, Stack } from "degen";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { CopyBlock, atomOneDark, dracula } from "react-code-blocks";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { connect, isAuthenticating, profile, logout } = useParticalAccount();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Partical</a> + <a href="">wagmi</a> +{" "}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.content}>
          <Stack align="center">
            {!profile ? (
              <Button
                prefix={<IconEth />}
                variant="secondary"
                loading={isAuthenticating}
                onClick={() => {
                  connect();
                }}
              >
                Sign in with Ethereum
              </Button>
            ) : (
              <Button
                variant="secondary"
                loading={isAuthenticating}
                onClick={() => {
                  logout();
                }}
              >
                Logout
              </Button>
            )}
            <Box>{profile && profile.username + " Connected"}</Box>
            <CopyBlock
              text={`
              const { profile , connect, isAuthenticating } = useParticalAccount();
              const { schema , createData , getDataById , updateDataById, getAllData } = useParticalSchema(:SchemaId);
            `}
              language="jsx"
              showLineNumbers={false}
              codeBlock
              theme={dracula}
            />
          </Stack>
        </div>
      </main>
    </div>
  );
};

export default Home;
